NandhaKumaranDentalClinic/NandhaKumaranDental/DentalCare/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('HealthCentre.urls')),
    path('admin/', admin.site.urls),
    path('medicalstore/', include(('MedicalStore.urls', 'MedicalStore'), namespace = "MedicalStore"))
]

NandhaKumaranDentalClinic/NandhaKumaranDental/HealthCentre/urls.py
from django.urls import path

from . import views
# from django.urls import path
# from .views import get_whatsapp_number

urlpatterns = [
    path('', views.login, name = "index"),
    path('register', views.register, name = "register"),
    path('doctors', views.doctors, name = "doctors"),
    path('login', views.login, name = "login"),
    path('emergency', views.emergency, name = "emergency"),
    path('logout', views.logout, name = "logout"),
    path('contactus', views.contactus, name = "contactus"),
    path('onlineprescription', views.onlineprescription, name = "onlineprescription"),
    path('doctorprofile', views.doctorprofile, name = "doctorprofile"),
    path('doctorappointments', views.doctorappointments, name = "doctorappointments"),
    path('searchAppointments', views.searchAppointments, name = "searchAppointments"),
    path('doctorappointmentsfalse', views.doctorappointmentsfalse, name = "doctorappointmentsfalse"),
    path('editAppointments/<pk>', views.editAppointments, name = 'editAppointments'),
    path('deleteappointment/<pk>', views.deleteappointment, name = 'deleteappointment'),
    
    # path('editAppointments', views.editAppointments, name = 'editAppointments')
]

# from django.urls import path
# from your_app.views import get_whatsapp_number

# urlpatterns = [
#     # Other URL patterns...
#     path('whatsapp-number/<int:number_id>/', get_whatsapp_number, name='whatsapp_number'),
# ]

NandhaKumaranDentalClinic/NandhaKumaranDental/MedicalStore/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('search', views.search, name = "search")
]

NandhaKumaranDentalClinic/NandhaKumaranDental/HealthCentre/models.py
from django.db import models
from Cryptodome.Hash import SHA256
from codecs import encode,decode
from django.utils import timezone


class Doctor(models.Model):
    name = models.CharField(max_length = 30)
    address = models.CharField(max_length = 100)
    contactNumber = models.CharField(unique = True, max_length = 10)
    email = models.EmailField(unique = True, max_length = 255)
    specialization = models.CharField(max_length = 100)
    passwordHash = models.CharField(max_length = 64)
    emailHash = models.CharField(max_length = 64)

    def __str__(self):
        return "Name : " + self.name + " Address : " + self.address + " Contact : " + self.contactNumber + " Email : " + self.email + " Specialization : " + self.specialization

class Patient(models.Model):
    name = models.CharField(max_length = 30)
    address = models.CharField(max_length = 100)
    contactNumber = models.CharField(max_length = 10)
    email = models.EmailField(unique = True, max_length = 255)
    rollNumber = models.CharField(unique = True, max_length = 8)
    passwordHash = models.CharField(max_length = 64)
    emailHash = models.CharField(max_length = 64)

    def __str__(self):
        return "Name : " + self.name + " Address : " + self.address + " Contact : " + self.contactNumber + " Email : " + self.email

class Prescription(models.Model):
    prescriptionText = models.CharField(max_length = 2000, default = "")
    prescribingDoctor = models.CharField(max_length= 2000, default= "")
    prescribingPatient = models.CharField(max_length= 2000, default= "")
    doctor = models.ForeignKey(Doctor, related_name = "doctorRecords", on_delete = models.CASCADE)
    patient = models.ForeignKey(Patient, related_name = "patientRecords", on_delete = models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add = True)
    isNew = models.BooleanField(default = True)
    isCompleted = models.BooleanField(default = False)
    symptoms = models.CharField(max_length = 2000)

    def __str__(self):
        return "\nDoctor :" + str(self.doctor) + "\n\nPatient :" + str(self.patient) + "\n\nPrescription : \n\n" + self.prescriptionText + "\n\n"

class Appointment(models.Model):
    time = models.TimeField(default=timezone.now)
    date = models.DateField(default=timezone.now)
    subject = models.CharField(max_length=2000)
    notes = models.TextField()
    appointmentpatient = models.CharField(max_length=2000, default = "")
    appointmentdoctor  = models.CharField(max_length=2000, default= "")
    AppointmentTimeStamp = models.DateTimeField(auto_now_add = True)#auto_now_add = True

    def __str__(self):
        return "\nDoctor :" + str(self.appointmentdoctor) + "\n\nPatient" + str(self.appointmentpatient) +"\n\nDate :"+ str(self.date) + "\n\nTime :" + str(self.time) + "\n\nSubject :" + str(self.subject) + "\n\nnotes :" + str(self.notes)
    
def passwordHasher(userPassword):
    """Function to return the hash of the password using SHA-256. Input is the password of the user in string."""
    userPassword = userPassword
    SHA256Engine = SHA256.new()
    userPassword = userPassword.encode()
    SHA256Engine.update(userPassword)
    passwordHash = SHA256Engine.digest()
    passwordHash = encode(passwordHash, 'hex')
    passwordHash = decode(passwordHash, 'utf-8')
    return passwordHash


def emailHasher(userEmail):
    """Function to return the hash of the email using SHA-256. Input is the email of the user in string."""
    userEmail = userEmail
    SHA256Engine = SHA256.new()
    userEmail = userEmail.encode()
    SHA256Engine.update(userEmail)
    emailHash = SHA256Engine.digest()
    emailHash = encode(emailHash, 'hex')
    emailHash = decode(emailHash, 'utf-8')
    return emailHash
    

NandhaKumaranDentalClinic/NandhaKumaranDental/HealthCentre/forms.py
from django.forms import ModelForm
from .models import Appointment
from django import forms
from .widgets import DatePickerInput, TimePickerInput, DateTimePickerInput


class AppointmentSet(forms.Form):
    # my_date_field = forms.DateField(widget=DatePickerInput)
    # my_time_field = forms.TimeField(widget=TimePickerInput)
    my_date_time_field = forms.DateTimeField(widget=DateTimePickerInput)

class AppointmentSetForm(ModelForm):
    class Meta:
        model = Appointment
        
        fields = ['subject', 'time', 'notes']

        widgets = {
            'time' : DateTimePickerInput(),
            
        }

class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        fields = "__all__"
# class TimeInput(forms.TimeInput, forms.DateInput):
#     timeInputType = 'time'
#     dateinputType = 'date'

# class AppointmentForm(ModelForm):
    # hour = forms.TimeField(widget=forms.Select(choices=[
    #     (hour, hour) for hour in range(0, 24)   
    # ]))
    # min = forms.TimeField(widget=forms.Select(choices=[
    #     (min, min) for min in range(0, 60)
    # ]))

    # class Meta:
    #     model = Appointment
    #     fields = ['time', 'date']
    #     widgets = {
    #         'time': TimeInput(),
    #     }
    #     # field_classes = {
    #     #     'time': 'form-control col-md-6',
    #     #     'min': 'form-control col-md-6',
    #     # }

NandhaKumaranDentalClinic/NandhaKumaranDental/HealthCentre/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Doctor, Patient, Prescription, passwordHasher, emailHasher, Appointment
from django.db.models import Count, Q
from django.contrib.auth.decorators import login_required
from .forms import AppointmentSet, AppointmentSetForm, AppointmentForm
from datetime import datetime, time
import datetime as dt
from django.utils import timezone
from django.shortcuts import render
import sys
if 'runserver' in sys.argv:
    from .Whatsapptestfile import whatsappApi, openWhatsapp

def index(request):
    """ Function for displaying main page of website. """
    
    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"HealthCentre/index.html")
    return responseHeadersModifier(response)

def register(request):
    """ Function for registering a student into the portal. """

    # If the user wants the page to get displayed

    if request.method == "GET":
        # Editing response headers so as to ignore cached versions of pages

        response =  render(request,"HealthCentre/registrationPortal.html")

        return responseHeadersModifier(response)
    
    # If the user wants to submit his/her information

    elif request.method == "POST":
        # Extracting the user information from the post request
        userFirstName = request.POST["userFirstNam"]
        userLastName = request.POST["userLastName"]
        userEmail = request.POST["userEmail"]
        userRollNo = request.POST["userRollNo"]
        userAddress = request.POST["userAddress"]
        userContactNo = request.POST["userContactNo"]
        userPassword = request.POST["userPassword"]
        userConfirmPassword = request.POST["userConfirmPassword"]

        # If both the passwords match
        if userPassword == userConfirmPassword:

            name = userFirstName + " " + userLastName

            # Encrypting password to store inside database
            passwordHash = passwordHasher(userPassword)

            # Encrypting email to store inside database
            emailHash = emailHasher(userEmail)

            # handleSubmit(request)
            # def handleSubmit(request):
            
            
            # Creating a patient object and saving insdie the database if patient is selected 
            userType = request.POST['userType']
            if userType == 'patient':
                # patient = Patient(rollNumber=request.POST['rollNumber'])
                patient = Patient(name = name,rollNumber = userRollNo, email = userEmail, passwordHash = passwordHash, address = userAddress, contactNumber = userContactNo, emailHash = emailHash )
                patient.save()
                    
            # Creating a patient object and saving insdie the database if patient is selected
            elif userType == 'doctor':
                doctor = Doctor(name = name, specialization= userRollNo, email = userEmail, passwordHash = passwordHash, address = userAddress, contactNumber = userContactNo, emailHash = emailHash)
                doctor.save()


            
            

            # Creating a patient object and saving insdie the database
            # patient = Patient(name = name,rollNumber = userRollNo, email = userEmail, passwordHash = passwordHash, address = userAddress, contactNumber = userContactNo, emailHash = emailHash )
            # patient.save()

            # Storing success message in the context variable
            context = {
                "message":"User Registration Successful. Please Login."
            }

            # Editing response headers so as to ignore cached versions of pages
            response = render(request, "HealthCentre/registrationPortal.html",context)
            return responseHeadersModifier(response)

        # If the passwords given don't match
        else:
            # Storing failure message in the context variable
            context = {
                "message":"Passwords do not match.Please register again."
            }

            # Editing response headers so as to ignore cached versions of pages
            response = render(request,"HealthCentre/registrationPortal.html",context)
            return responseHeadersModifier(response)

    # For any other method of request, sending back the registration page.
    else:

        # Editing response headers so as to ignore cached versions of pages
        response = render(request,"HealthCentre/registrationPortal.html")
        return responseHeadersModifier(response)


def doctors(request):
    """Function to send information about the doctors available to the user. """

    # Storing doctors available in the context variable
    context = {
        "doctors" : Doctor.objects.all()
    }

    # Editing response headers so as to ignore cached versions of pages
    response = render(request,"HealthCentre/doctors.html",context)
    return responseHeadersModifier(response)


def login(request):
    """ Function for logging in the user. """

    # Calling session variables checker
    request = requestSessionInitializedChecker(request)

    # If the request method is post
    if request.method == "GET":
        try:

            # If the user is already logged in inside of his sessions, and is a doctor, then no authentication required
            if request.session['isLoggedIn'] and request.session['isDoctor']:
                # Accessing the doctor user and all his/her records
                doctor = Doctor.objects.get(emailHash = request.session['userEmail'])
                records = doctor.doctorRecords.all()
                # Getting the count of the new prescriptions pending
                numberNewPendingPrescriptions = doctor.doctorRecords.aggregate(newnewPendingPrescriptions = Count('pk', filter =( Q(isNew = True) & Q(isCompleted = False) ) ))['newnewPendingPrescriptions']
                # Storing the same inside the session variables
                request.session['numberNewPrescriptions'] = numberNewPendingPrescriptions

                # Storing the required information inside the context variable
                context = {
                    "message" : "Successfully Logged In.",
                    "isAuthenticated" : True,
                    "user": records.order_by('-timestamp'),
                    "prescriptions" : Prescription.objects.all().order_by('timestamp')
                }
                
                # Editing response headers so as to ignore cached versions of pages
                response = render(request,"HealthCentre/prescriptionPortal.html", context)
                return responseHeadersModifier(response)
            
            # If the user is already logged in inside of his sessions, and is a patient, then no authentication required
            elif request.session['isLoggedIn'] and (not request.session['isDoctor']):

                # Accessing the patient user and all his/her records
                patient = Patient.objects.get(emailHash = request.session['userEmail'])
                records = patient.patientRecords.all()

                # Getting the count of the new prescriptions pending
                numberNewPrescriptions = patient.patientRecords.aggregate(newCompletedPrescriptions = Count('pk', filter =( Q(isNew = True) & Q(isCompleted = True) ) ) )['newCompletedPrescriptions']

                # Storing the same inside the session variables
                request.session['numberNewPrescriptions'] = numberNewPrescriptions

                # Updating the completed records
                for record in records:
                    if record.isCompleted:
                        record.isNew = False
                        record.save()

                # Storing the required information inside the context variable
                context = {
                    "message" : "Successfully Logged In.",
                    "isAuthenticated" : True,
                    "user": records.order_by('-timestamp')
                    }

                # Editing response headers so as to ignore cached versions of pages
                # response = render(request,"HealthCentre/prescriptionPortal.html")
                response = render(request,"HealthCentre/userPatientProfilePortal.html", context)
                return responseHeadersModifier(response)

            else:
                # Editing response headers so as to ignore cached versions of pages
                response = render(request,"HealthCentre/loginPortal.html")
                return responseHeadersModifier(response)

        # If any error occurs, sending back a new blank page
        except:

            # Editing response headers so as to ignore cached versions of pages
            response = render(request,"HealthCentre/loginPortal.html")
            return responseHeadersModifier(response)

    # If the request method is post
    elif request.method == "POST":

        # Extracting the user information from the post request
        userName = request.POST["useremail"]
        userPassword = request.POST["userpassword"]

        # If such a patient exists
        try:
            patient = Patient.objects.get(email = userName)

            # Storing required session information
            request.session['isDoctor'] = False

        # Otherwise trying if a doctor exists
        except Patient.DoesNotExist:
            try:
                doctor = Doctor.objects.get(email = userName)

                # Storing required session information
                request.session['isDoctor'] = True     

            # If no such doctor or patient exists
            except Doctor.DoesNotExist:

                # Storing message inside context variable
                context = {
                    "message":"User does not exist.Please register first."

NandhaKumaranDentalClinic/NandhaKumaranDental/HealthCentre/templates/HealthCentre/contactus.html
{% extends "HealthCentre/layout.html" %}

{% block title %}
NDC-Contact us
{% endblock %}

{% block bodytag %}

  {% load static %}
  <body background="{% static 'HealthCentre/images/i6.jpg' %}" style="background-size: auto auto;">

{% endblock %}

{% block body %}
    <br>

    <div class="jumbotron jumbotron-fluid" style = "margin-left:5%;margin-right:5%;background:rgba(0,0,0,0.6);color:white;">
        <div class="container">

            <h1 >Address</h1>

            <p class="lead">****ADDRESS********</p>
            <button class="btn btn-info" >Pin Code : ######</button>

            <br>
            <br>

            <h1>Email</h1>

            <p class="lead">Suggestions and feedback are thoroughly welcomed.</p>
            <button class="btn btn-info" >healthcentre@gmail.com</button>

            <br>
            <br>

            <h1 >Reception Contact Numbers</h1>

            <p class="lead">Please feel free to call us anytime. 24 x 7 Helpline Availability.</p>
            <button class="btn btn-info" >Contact Numbers : 0141-3562834, 0141-35682104</button>

        </div>
    </div>

{% endblock %}

NandhaKumaranDentalClinic/NandhaKumaranDental/HealthCentre/templates/HealthCentre/index.html
{% extends "HealthCentre/layout.html" %}


{% block title %}
    'Nandakumaran Dental Care'
{% endblock %}


{% block style %}

    .carousel-item{
        height: 500px;
      }
    .carousel-item img{
        height: 500px;
      }

{% endblock %}


{% block bodytag %}

    {% load static %}
    <body background="{% static 'HealthCentre/images/plain.jpg' %}" style="background-size: auto auto;">

{% endblock %}


{% block body %}

    <div style="text-align:center;margin: 0 auto;"class="alert alert-danger" role="alert">
        Get a checkup immediately!!
    </div>


    <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>

        <!-- <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="{% static 'HealthCentre/images/dent.jpg' %}" class="d-block w-100 " alt="Dental care" >
                <div class="carousel-caption d-none d-md-block ">
                    <h5>Welcome To Dr. Nandhakumaran Dental Care</h5>
                    <p>Good health is one of life's greatest blessings. Eat well!</p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="{% static 'HealthCentre/images/dent1.jpg' %}" class="d-block w-100 " alt="Beautiful smile" >
                <div class="carousel-caption d-none d-md-block">
                    <h5>Smile please, always!</h5>
                </div>
            </div>

            <div class="carousel-item">
                <img src="{% static 'HealthCentre/images/dent3.jpg' %}" class="d-block w-100 " alt="get altered" >
                <div class="carousel-caption d-none d-md-block">
                    <h5>To enjoy the healthy food, you must brush your teeth!</h5>
                </div>
            </div>

        </div> -->

        <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

    </div>

    {% if request.session.isLoggedIn %}
      {% else %}
      <div class="jumbotron" style="margin: 0 auto;">
          <h1 class="display-4">Hey there! Haven't registered yet?!</h1>
          <p class="lead">Register yourself today and get access to all the benefits of the Health Centre!</p>
          <hr class="my-4">
          <p>You must be a member to have access to this facility.</p>
          <a class="btn btn-primary btn-lg" href="{% url 'register' %}" role="button">Register</a>
      </div>
    {% endif %}

    <div>
        <hr class="my-4">
        <h1 class ="display-3"style="text-align:center;color:black">BENEFITS</h1>
        <li class="dropdown-divider" style="margin-left:25%;margin-right:25%;border-color:black"></li>

        <div class="row"style="margin: 0 auto;" >

            <div class="col-sm-6" style = "margin-top:2%">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">Medical Store </h5>
                        <li class="dropdown-divider" style="margin-right:15%"></li>
                        <p class="card-text">Avail benefits of online medical store!</p>
                        <a href="{% url 'MedicalStore:index' %}" class="btn btn-primary">MEDICAL STORE</a>

                    </div>
                </div>
            </div>

            <div class="col-sm-6" style="margin-top:2%">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">Emergency Ambulance</h5>
                        <li class="dropdown-divider" style="margin-right:15%"></li>
                        <p class="card-text">Get immediate ambulance in emergency situation.</p>
                        <a href="{% url 'emergency' %}" class="btn btn-primary">EMERGENCY</a>

                    </div>
                </div>
            </div>

      </div>

        <div class="row"style="margin: 0 auto;" >

            <div class="col-sm-6" style ="margin-top:2%">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">Online Prescription</h5>
                        <li class="dropdown-divider" style="margin-right:15%"></li>
                        <p class="card-text">Get online hassle-free prescription from doctor.</p>
                        <a href="{% url 'onlineprescription' %}" class="btn btn-primary">ONLINE PRESCRIPTION</a>

                    </div>
                </div>
            </div>

            <div class="col-sm-6" style="margin-top:2%">
                <div class="card">
                    <div class="card-body">

                        <h5 class="card-title">Contact Us</h5>
                        <li class="dropdown-divider" style="margin-right:15%"></li>
                        <p class="card-text">24 x 7 Help Line Availability.</p>
                        <a href="{% url 'contactus' %}" class="btn btn-primary">CONTACT US</a>

                    </div>
                </div>
            </div>

        </div>
    </div>

    <div id="Footer">
        <h6 style="text-align:center;color:black;background-color:#dddddd;margin: 0 auto;">
            <hr class="my-4"style="margin: 0 auto;" >
                ©2023 All Rights Reserved, Dr. Nandakumaran
                <br>
                <br>
        </h6>
    <div>

{% endblock %}

NandhaKumaranDentalClinic/NandhaKumaranDental/HealthCentre/templates/HealthCentre/layout.html
<!-- {% load static %} -->


<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

        <title>{% block title %} Dental CLinic {% endblock %}</title>

        <!-- <style>{% block style %}{% endblock %}</style> -->

        <script src="{% static 'HealthCentre/javascript/windowHistory.js' %}"></script>

        {% block script %}
            Dr.Nandhakumaram Dental 
        {% endblock %}
        
    </head>
    
    {% block bodytag %}
        {% load static %}
        <body background="{% static 'HealthCentre/images/plain.jpg' %}" style="background-size: auto auto;">
    {% endblock %}



    <nav class="navbar navbar-expand-lg navbar-light bg-transparent" >
        {% if request.session.isLoggedIn %}
            <a class="navbar-brand" href="/"><h3 style="color:black;text-align:center">Hi,{% if request.session.isDoctor %} Dr.{% endif %} {{ request.session.Name }}</h3></a>
        {% else %}
            <a class="navbar-brand" href="/"><h2 style="color:black;text-align:center">Dr. Nandakumaran Dental CLinic</h2></a>
        {% endif %}

        <!-- <img src="{% static 'HealthCentre/images/jdh10.png' %}" style="width:5%;height:5%;"></img> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <!-- <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}" style="color:black">Home <span class="sr-only">(current)</span></a>
                </li> -->

                {% if request.session.isLoggedIn %}
                    {% if request.session.isDoctor %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}" style="color:black">Your Prescriptions <span class="badge badge-primary badge-pill">{{ request.session.numberNewPrescriptions }} NEW</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'doctorappointmentsfalse' %}" style="color:black">Your Appointments <span class="badge badge-primary badge-pill">{{ request.session.numberNewPrescriptions }} NEW</span></a>
                    </li>
                    {% endif %}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}" style="color:black">Login</a>
                      </li>
                {% endif %}

                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color:black" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Options
                    </a> -->
                    <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown"> -->

                        <!-- <a class="dropdown-item" href="{% url 'MedicalStore:index' %}">Medicine Store</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'doctors' %}">Doctors</a> -->
                        <div class="dropdown-divider"></div>
                        <li class = "nav-item">
                            <a class="nav-link" align = "right" style="color:black" href="{% url 'contactus' %}">Contact Us</a>
                        </li>
                        

                        {% if request.session.isLoggedIn %}
                            <div class="dropdown-divider"></div>
                            <li class = "nav-item">
                                <a class="nav-link" style="color:black" href="{% url 'logout' %}">Logout</a>
                            </li>
                        {% endif %}

                    <!-- </div> -->
                </li>

                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'onlineprescription' %}" style="color:black">Prescription</a>
                </li> -->

                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'emergency' %}" style="color:black"><span style="background-color:red" class="badge badge-secondary">EMERGENCY</span></a>
                </li> -->

            </ul>

            <!-- <form class="form-inline my-2 my-lg-0" method="post" action="{% url 'MedicalStore:search' %}">
              {% csrf_token %}
                <input name = "searchQuery" class="form-control mr-sm-2" type="search" placeholder="Search Medicine" aria-label="Search">
                <button class="btn btn-outline-success my-1 my-sm-0" type="submit">Search</button>
            </form> -->

        </div>
    </nav>
    <li class="dropdown-divider" style="margin-top:0px;margin-bottom:0px;border-color:black"></li>

{% block body %}

{% endblock %}

            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
            
        </body>
    </html>